server:
  port: 8082
#数据库配置
spring:
  mail:
    host: smtp.qq.com
    #发送者邮箱
    username: 1355252692@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: rcszgvtllfyuighi
    #端口号465或587
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    protocol: smtps
    #其他参数
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  main:
    allow-circular-references: true
  datasource:
    hikari:
      auto-commit: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root #你本地的数据库用户名
    password: 1355252692Gxh #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#Mybatis配置
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql